apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-cronjob
spec:
  # 01/01 00:00 JST This is sample
  schedule: 00 15 31 12 *
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        spec:
          initContainers:
          - name: get-chart
            image: alpine:latest
            command: ["/bin/sh","-c"]
            args: ["apk add git && git clone https://${PAT}@github.com/${OWNER}/${REPO} /chart"]
            volumeMounts:
            - mountPath: /chart
              name: chart
            envFrom:
            - secretRef:
                name: helm-cronjob
          containers:
          - name: helm
            image: ghcr.io/mikutas/just-helm:v3.13.0
            args:
            - "version"
            volumeMounts:
            - mountPath: /chart
              name: chart
          volumes:
          - name: chart
            emptyDir: {}
          restartPolicy: Never
          serviceAccountName: helm-cronjob
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-cronjob
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-as-editor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: helm-cronjob
  namespace: default
