name: Docker

on:
  pull_request:

env:
  IMAGE_NAME: greeter-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
